version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: spaceapss-redis
    ports:
      - "6379:6379"   # Redis
      - "8001:8001"   # Redis Insight
    environment:
      - REDIS_ARGS=--save 60 1000
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - spaceapss

  # Opcional: rodar API no Docker
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: spaceapss-api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - REDIS_URL=redis://redis:6379
  #   env_file:
  #     - .env
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - spaceapss

volumes:
  redis_data:

networks:
  spaceapss:
    driver: bridge
